# Generated by Django 4.2.21 on 2025-05-13 09:33

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hallenbad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=64)),
                ('point_id', models.IntegerField(unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('ort', models.CharField(blank=True, max_length=255, null=True)),
                ('ort_bezeichnung', models.CharField(blank=True, max_length=255, null=True)),
                ('strasse', models.CharField(blank=True, max_length=255, null=True)),
                ('strasse_bezeichnung', models.CharField(blank=True, max_length=255, null=True)),
                ('hausnr', models.CharField(blank=True, max_length=10, null=True)),
                ('plz', models.CharField(blank=True, max_length=10, null=True)),
                ('telefon', models.CharField(blank=True, max_length=20, null=True)),
                ('fax', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('oeffnungszeiten', models.JSONField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
