# Generated by Django 4.2.21 on 2025-05-14 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapi', '0002_fussballplatz_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='phone',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
